; colorice theme — shado default (regenerate via: colorice <wallpaper> --apply)

[colors]
background  = #191724
foreground  = #e3c7fc
cursor      = #f1c4e0

color0      = #140a1d
color1      = #B52A5B
color2      = #FF4971
color3      = #8897F4
color4      = #bd93f9
color5      = #E9729D
color6      = #F18FB0
color7      = #f1c4e0
color8      = #a8899c
color9      = #B52A5B
color10     = #FF4971
color11     = #8897F4
color12     = #bd93f9
color13     = #E9729D
color14     = #F18FB0
color15     = #f1c4e0
