# colorice theme — shado default (regenerate via: colorice <wallpaper> --apply)

set $background  #191724
set $foreground  #e3c7fc
set $cursor      #f1c4e0

set $color0      #140a1d
set $color1      #B52A5B
set $color2      #FF4971
set $color3      #8897F4
set $color4      #bd93f9
set $color5      #E9729D
set $color6      #F18FB0
set $color7      #f1c4e0
set $color8      #a8899c
set $color9      #B52A5B
set $color10     #FF4971
set $color11     #8897F4
set $color12     #bd93f9
set $color13     #E9729D
set $color14     #F18FB0
set $color15     #f1c4e0

# Window colors            border       background   text         indicator    child_border
client.focused             $color4      $color4      $background  $color6      $color4
client.focused_inactive    $color8      $color8      $foreground  $color8      $color8
client.unfocused           $background  $background  $color8      $background  $background
client.urgent              $color1      $color1      $foreground  $color1      $color1
